### PR TITLE
Rebase hifi3 patches on 17.0.1

### PR DESCRIPTION
**Pull request by gerekon**
Rebase patches from #85 onto 17.0.1 branch

### CODE REVIEW

**Comment by gerekon** [comment]
@maciej-czekaj Could you kindly check rebased patches? After rebasing I faced several build errors due to API changes. The fixes for them are in several last commits like `tmp: Fix ...`.

`DROPME: ...` commits can be ignored they were picked from #87 and added just to run build/test pipelines for this PR.

**Comment by gerekon** [comment]
Looks like 2 clang tests fail 
1) `xtensa-xtbool-intrinsics.c` due to `-no-opaque-pointers` option. I will fix this.
2) `xtensa-abi.c` boolean feature test fails. Need to investifgate

**Comment by maciej-czekaj** [comment]
@gerekon Thanks for the heads up! I will fix it.

**Comment by maciej-czekaj** [comment]
@gerekon I have pushed 2 fixes in #89 
 - e89f8ed88531 [Xtensa] Fix reg scavenging in XtensaRegisterInfo
 - 3dc231944615 [Xtensa] Fix LLVM argument size for bool vectors.

**Comment by gerekon** [comment]
Close in favor of #89 a7

**Comment by gerekon** [comment]
merged

**Pull request closed without merging**
