### PR TITLE
[Xtensa] Add MINMAX/CLAMPS features (LLVM-278)

### PR DESCRIPTION
**Pull request by zRedShift**
- [Xtensa] Add MINMAX feature
- [Xtensa] Add CLAMPS feature

### CODE REVIEW

**Comment by andreisfr** [comment]
Hi, @zRedShift! Thank you very much for your pull requests. We investigating them and we will prepare update.

**Comment by zRedShift** [comment]
@andreisfr Sure, let me know if you want me to roll up all my PR's into one for easier checking (like [here](https://github.com/zRedShift/llvm-project-espressif/tree/my-branch)).

There was another "easy win" in my investigations, the ABS intstruction, hopefully you don't mind me adding it to this PR.

**Comment by ramtej** [comment]
Gentlemen, do we have an idea yet as to when the PR can be merged? Thx!

**Comment by gerekon** [comment]
Closed by 26ca9b6b7420596520c37d6e1574a1ea91dfc630 and c81a5b8cfd3a5864eadd1726dea225639eba6ecc

**Pull request closed without merging**
