### PR TITLE
HIFI3 fixes for 17.0.1 release  (LLVM-319)

### PR DESCRIPTION
**Pull request by maciej-czekaj**
This PR contains the following fixes for pr #88  :
  - e89f8ed88531  [Xtensa] Fix reg scavenging in XtensaRegisterInfo
  - 3dc231944615 [Xtensa] Fix LLVM argument size for bool vectors.

### CODE REVIEW

**Comment by gerekon** [comment]
Ran pipelines

**Comment by gerekon** [comment]
@maciej-czekaj Looks like test on Windows fails

**Comment by gerekon** [comment]
@maciej-czekaj I merged GH PR pipeline #87. So you can drop `DROPME: ...` commits. All your pushes should run build/test pipeline automatically now.

**Comment by gerekon** [comment]
@maciej-czekaj If you do not mind I will disable this test for Windows and merge this PR

**Comment by maciej-czekaj** [comment]
@gerekon I don't mind at all if you merge it by disabling Windows tests. Let's log a bug for that.

**Comment by gerekon** [comment]
merged

**Pull request closed without merging**
